# Generated by Django 5.0.6 on 2024-06-24 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_book_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='user',
        ),
        migrations.AddField(
            model_name='book',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, related_name='borrowed_books', to=settings.AUTH_USER_MODEL),
        ),
    ]
